name: "MOVA Pilates - Development"

services:
  database:
    image: postgres:17
    container_name: mova_pilates_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      TZ: Europe/Paris
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - mova_pilates_data:/var/libs/postgresql/data

  redis:
    image: redis:alpine
    container_name: mova_pilates_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always

volumes:
  mova_pilates_data:
  pgadmin_data:

networks:
  postgres-network:
    driver: bridge
