version: "3.9"
name: "MOVA Pilates - Production"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: ../
      dockerfile: ./apps/api/Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3001
      APP_URL: ${APP_URL}
      API_URL: http://api:3001
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
    depends_on:
      - db
      - redis
    ports:
      - "3001:3001"

  dashboard:
    build:
      context: ../
      dockerfile: ./apps/dashboard/Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      VITE_API_URL: http://api:3001
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  db_data:
  redis_data:
